# Azure DevOps pipeline template used to setup the Node project:
# 1. checkout code
# 2. setup correct node version
# 3. install node dependencies

parameters:

# the branch, tag or commit to checkout
- name: 'gitReference'
  type: string
  default: 'none'

# whether code must be checked-out with persisted credentials
- name: 'persistCredentials'
  type: boolean
  default: false

# optional sub path where the project to be initialized is located. To be used on repository with multiple projects. 
- name: 'projectDir'
  type: string
  default: '.' # current folder is default

# if not set, the Node version is read from .node-version or .nvmrc, in that order
- name: 'nodeVersion'
  type: string
  default: 'none'
  
steps:
- checkout: self
  displayName: 'Checkout'
  persistCredentials: ${{ parameters.persistCredentials }}

# This is needed because the pipeline may point to a different commit than expected
# The common case is when the previous stage pushed another commit
- ${{ if ne(parameters.gitReference, 'none') }}:
  - bash: |
      set -euo pipefail
      git fetch
      git checkout "$GIT_REFERENCE"
    env:
      GIT_REFERENCE: ${{ parameters.gitReference }}
    displayName: 'Checkout reference'  

# If a Node version is defined explicitly by parameter, such version is used
# Otherwise, the version is read from .node-version or .nvmrc
- ${{ if ne(parameters.nodeVersion, 'none') }}:
  - bash: |
      set -euo pipefail
      echo "##vso[task.setvariable variable=NODE_VERSION]$NODE_VERSION_PARAM"
    env:
      NODE_VERSION_PARAM: ${{ parameters.nodeVersion }}
    workingDirectory: ${{ parameters.projectDir }}
    displayName: 'Determine Node.js version from template param'
- ${{ if eq(parameters.nodeVersion, 'none') }}:
  - bash: |
      set -euo pipefail
      if [[ -f .node-version ]]; then
        SOURCE_FILE='.node-version'
      elif [[ -f .nvmrc ]]; then
        SOURCE_FILE='.nvmrc'
      else
        echo "Neither .node-version nor .nvmrc exists in $(pwd)" >&2
        exit 1
      fi
      FROM_SOURCE="$(<"$SOURCE_FILE")"
      if [[ -z "$FROM_SOURCE" ]]; then
        echo "$SOURCE_FILE is empty" >&2
        exit 1
      fi
      echo "Node.js version from $SOURCE_FILE: $FROM_SOURCE"
      echo "##vso[task.setvariable variable=NODE_VERSION]$FROM_SOURCE"
    workingDirectory: ${{ parameters.projectDir }} 
    displayName: 'Determine Node.js version from source'

- task: UseNode@1
  inputs:
    version: $(NODE_VERSION)
  displayName: 'Set up Node.js'

- bash: |
    set -euo pipefail
    corepack enable
    YARN_CACHE_DIR=$(yarn config get cacheFolder)
    echo "Yarn cache dir: $YARN_CACHE_DIR"
    echo "##vso[task.setvariable variable=YARN_CACHE_FOLDER]$YARN_CACHE_DIR"
  workingDirectory: ${{ parameters.projectDir }}
  displayName: 'Enable Corepack & Get Yarn cache folder'

- task: Cache@2
  inputs:
    key: 'yarn | "$(Agent.OS)" | ${{ parameters.projectDir }}/yarn.lock'
    restoreKeys: |
       yarn | "$(Agent.OS)"
    path: $(YARN_CACHE_FOLDER)
  displayName: 'Cache Yarn packages'

- bash: |
    set -euo pipefail
    yarn install --immutable
  workingDirectory: ${{ parameters.projectDir }}    
  displayName: 'Install node modules'