# Azure DevOps pipeline template used to build bundle.
parameters:
  - name: 'env'
    type: string
    default: ''

  - name: 'vite_deploy_path'
    type: string
    default: ''

  - name: 'vite_api_timeout'
    type: string
    default: ''

  - name: 'vite_apihost'
    type: string
    default: ''

  - name: 'vite_fileshare_apihost'
    type: string
    default: ''

steps:
- bash: |
    chmod +x env.sh
    env -i \
      PU_ENV=${{ parameters.env }} \
      PU_VITE_DEPLOY_PATH=${{ parameters.vite_deploy_path }} \
      PU_VITE_API_TIMEOUT=${{ parameters.vite_api_timeout }} \
      PU_VITE_APIHOST=${{ parameters.vite_apihost }} \
      PU_VITE_FILESHARE_APIHOST=${{ parameters.vite_fileshare_apihost }} \
      bash env.sh

  displayName: 'Populate environment file'
