name: 'PR title check'
on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  pr-title-check:
    runs-on: ubuntu-latest
    steps:
      - uses: Slashgear/action-check-pr-title@76166c63ec0b25cdbe693e5e972e83ca186313fb # v6.0.0 (node24)
        with:
          regexp: '((feat|fix|chore|ci|test|build|docs|perf|refactor|breaking): \[P4ADEV(-[0-9]{2,4})?\] .+)|(Bump .+)'
          helpMessage: "Example: 'feat: [P4ADEV-1041] example of title'"
